apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    role: pingdirectory
  name: pingdirectory-admin
spec:
  externalTrafficPolicy: Local
  ports:
  - name: ldaps
    port: 636
  selector:
    role: pingdirectory
  type: LoadBalancer
