version: "3.1"

services:
  pingdatasync:
    image: pingidentity/pingdatasync
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/server-profile-pingidentity-simple-sync.git
      - SERVER_PROFILE_PATH=pingdatasync
    deploy:
      replicas: 1
    networks:
      - pingnet
    volumes:
      - ${DEVOPS_IN_BASE}/pd-labs-vol:/opt/stuff
      - ${DEVOPS_OUT_BASE}/sync-lab03/pingdatasync:/opt/out

  pingdataconsole:
    image: pingidentity/pingdataconsole
    deploy:
      replicas: 1
    ports:
      - 8080:8080
    networks:
      - pingnet
        
networks:
    pingnet:
