kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- https://github.com/pingidentity/pingidentity-devops-getting-started/20-kubernetes/01-standalone/pingdirectory
- https://github.com/pingidentity/pingidentity-devops-getting-started/20-kubernetes/01-standalone/pingdataconsole
- pingdatasync
- pingdataconsole-ingress.yaml
- pingdirectory-ingress.yaml

patches:
- target:
    kind: StatefulSet
    name: pingdirectory
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env
      value:
        - name: SERVER_PROFILE_URL
          value: "https://github.com/pingidentity/pingidentity-server-profiles-playground.git"
        - name: SERVER_PROFILE_PATH
          value: "austin-training/pingdirectory"
        - name: SERVER_PROFILE_BRANCH
          value: "austin-k8s"
        - name: ORCHESTRATION_TYPE
          value: "kubernetes"
        - name: K8S_STATEFUL_SET_NAME
          value: "pingdirectory"
        - name: K8S_STATEFUL_SET_SERVICE_NAME
          value: "pingdirectory"
        - name: MAKELDIF_USERS
          value: "1000"
        - name: TAIL_LOG_FILES
          value: ""
- target:
    kind: StatefulSet
    name: pingdirectory
  patch: |-
    - op: add
      path: /spec/replicas
      value: 2
- target:
    kind: StatefulSet
    name: pingdirectory
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value: [{"name":"out-dir","mountPath":"/opt/out"}]
- target:
    kind: StatefulSet
    name: pingdirectory
  patch: |-
    - op: add
      path: /spec/volumeClaimTemplates
      value: [{"metadata":{"name":"out-dir"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"pingdirectory-gp2"}}]
- target:
    kind: StatefulSet
    name: pingdirectory
  patch: |-
    - op: add
      path: /spec/template/spec/volumes
      value: [{"name":"out-dir","persistentVolumeClaim":{"claimName":"out-dir"}}]
