apiVersion: v1
kind: Service
metadata:
  name: pingdatasync
  labels:
    app: pingdatasync
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    app: pingdatasync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingdatasync
  labels:
    app: pingdatasync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingdatasync
  template:
    metadata:
      name: pingdatasync
      labels:
        app: pingdatasync
    spec:
      containers:
      - name: pingdatasync
        image: pingidentity/pingdatasync:edge
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
        - name: SERVER_PROFILE_URL
          value: "https://github.com/pingidentity/pingidentity-server-profiles-playground.git"
        - name: SERVER_PROFILE_PATH
          value: "austin-training/pingdatasync"
        - name: SERVER_PROFILE_BRANCH
          value: "austin-k8s"
        envFrom:
        - secretRef:
            name: devops-secret
            optional: true
