version: "3.1"

services:
  pingdirectory:
    image: pingidentity/pingdirectory
    environment:
      # - SERVER_PROFILE_URL=...git repo...
      # - SERVER_PROFILE_PATH=...path in git repo...
      - VERBOSE=false
    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet
    volumes:
      - ${DEVOPS_IN_BASE}/pd-student:/opt/in
      - ${DEVOPS_IN_BASE}/pd-labs-vol:/opt/stuff
      - ${DEVOPS_OUT_BASE}/pd-lab01/pingdirectory:/opt/out
                    
  pingdataconsole:
    image: pingidentity/pingdataconsole
    ports:
      - 8080:8080
    networks:
      - pingnet

networks:
    pingnet:
