version: "3.1"

services:  
  pingfederate:
    image: pingidentity/pingfederate
    environment:
      #- SERVER_PROFILE_URL=https://github.com/pingidentity/server-profile-pingidentity-baseline.git
      #- SERVER_PROFILE_PATH=pingfederate
       - VERBOSE=true
    deploy:
      replicas: 1
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet
    volumes:
      - ${DEVOPS_IN_BASE}/poc-pingfederate:/opt/in
      - ${DEVOPS_IN_BASE}/poc-labs-vol:/opt/stuff
      - ${DEVOPS_OUT_BASE}/poc-lab01/pingfederate:/opt/out

  pingdirectory:
    image: pingidentity/pingdirectory
    environment:
      # - SERVER_PROFILE_URL=...git repo...
      # - SERVER_PROFILE_PATH=...path in git repo...
      - VERBOSE=false
    ports:
      - 1389:389
      - 1636:636
      - 1443:443
    networks:
      - pingnet
    volumes:
      - ${DEVOPS_IN_BASE}/pd-student:/opt/in
      - ${DEVOPS_IN_BASE}/poc-labs-vol:/opt/stuff
  #    - ${DEVOPS_OUT_BASE}/poc-lab01/pingdirectory:/opt/out

  pingdataconsole:
    image: pingidentity/pingdataconsole
    deploy:
      replicas: 1
    ports:
      - 8080:8080
    networks:
      - pingnet
        
networks:
    pingnet: