version: "3.1"

services:
  pingdirectory:
    image: pingidentity/pingdirectory
    volumes:
      - /tmp/server-profile-pingidentity-simple-sync/pingdirectory:/opt/in
    # environment:
    #   - SERVER_PROFILE_URL=https://github.com/pingidentity/server-profile-pingidentity-simple-sync.git
    #   - SERVER_PROFILE_PATH=pingdirectory
      # - VERBOSE=true
    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet

  pingdatasync:
    image: pingidentity/pingdatasync
    # environment:
    #   - SERVER_PROFILE_URL=https://github.com/pingidentity/server-profile-pingidentity-simple-sync.git
    #   - SERVER_PROFILE_PATH=pingdatasync
    volumes:
      - /tmp/server-profile-pingidentity-simple-sync/pingdatasync:/opt/in
    ports:
      - 3636:636
      - 3443:443
    networks:
      - pingnet
  
  pingdataconsole:
    image: pingidentity/pingdataconsole
    ports:
      - 8080:8080
    networks: 
      - pingnet  
              
networks:
    pingnet:
